/**
 * RemoteMonitor — watches Codex rollout JSONL files for new AI messages
 * generated by the desktop Codex client, then pushes them to Feishu.
 *
 * Usage:
 *   const monitor = new RemoteMonitor(() => targetProvider.listTargets());
 *   monitor.setSendFn((chatId, text) => sendToFeishu(chatId, text));
 *   // toggle per chat via monitor.toggle(chatId)
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { DatabaseSync } from 'node:sqlite';
import type { Target } from './types.js';

const CODEX_DB_PATH = path.join(os.homedir(), '.codex', 'state_5.sqlite');
const POLL_INTERVAL_MS = 2500;
const REFRESH_TARGETS_EVERY_MS = 30_000;

type SendFn = (chatId: string, text: string) => Promise<void>;
type GetTargets = () => Target[];

interface WatchEntry {
  rolloutPath: string;
  lastOffset: number;
  threadId: string;
}

/**
 * Extract agent messages and token counts from newly-appended JSONL bytes.
 *
 * The Codex desktop client writes rollout files in this format:
 *   { type: 'event_msg',      payload: { type: 'agent_message', message: '<text>' } }
 *   { type: 'event_msg',      payload: { type: 'token_count',   info: { last_token_usage: { output_tokens, reasoning_output_tokens } } } }
 *   { type: 'event_msg',      payload: { type: 'task_complete' } }
 *   { type: 'response_item',  payload: { type: 'message', role: 'assistant', content: [...] } }
 *
 * NOTE: This is completely different from the SDK streaming events (item.completed etc)
 * that are used when bridging via the API.
 */
export interface ExtractResult {
  texts: string[];
  outputTokens: number;  // from token_count events (sum of last_token_usage.output_tokens + reasoning)
}

function extractFromChunk(raw: string): ExtractResult {
  const texts: string[] = [];
  let outputTokens = 0;

  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      const obj = JSON.parse(trimmed) as Record<string, unknown>;
      if (obj.type !== 'event_msg') continue;

      const payload = obj.payload as Record<string, unknown> | undefined;
      if (!payload) continue;

      if (payload.type === 'agent_message' && typeof payload.message === 'string' && payload.message) {
        texts.push(payload.message);
      } else if (payload.type === 'token_count') {
        const info = payload.info as Record<string, unknown> | undefined;
        const last = info?.last_token_usage as Record<string, unknown> | undefined;
        if (last) {
          outputTokens += Number(last.output_tokens ?? 0) + Number(last.reasoning_output_tokens ?? 0);
        }
      }
    } catch { /* skip malformed lines */ }
  }

  return { texts, outputTokens };
}

export class RemoteMonitor {
  private watchers = new Map<string, WatchEntry>();       // threadId → watcher state
  private enabledChats = new Set<string>();               // chatIds with remote mode ON
  private sendFn: SendFn | null = null;
  private pollTimer: NodeJS.Timeout | null = null;
  private lastRefresh = 0;

  constructor(private readonly getTargets: GetTargets) {}

  /** Register the function that sends a proactive message to a Feishu chat. */
  setSendFn(fn: SendFn): void {
    this.sendFn = fn;
  }

  /**
   * Toggle remote mode for a chat.
   * Returns true if now enabled, false if now disabled.
   */
  toggle(chatId: string): boolean {
    if (this.enabledChats.has(chatId)) {
      this.enabledChats.delete(chatId);
      if (this.enabledChats.size === 0) this.stopPolling();
      return false;
    } else {
      this.enabledChats.add(chatId);
      // Initialize watcher offsets to END of current files so we only see future events
      this.initWatchers();
      this.ensurePolling();
      return true;
    }
  }

  isEnabled(chatId: string): boolean {
    return this.enabledChats.has(chatId);
  }

  private ensurePolling(): void {
    if (this.pollTimer) return;
    this.pollTimer = setInterval(() => this.poll(), POLL_INTERVAL_MS);
  }

  private stopPolling(): void {
    if (this.pollTimer) {
      clearInterval(this.pollTimer);
      this.pollTimer = null;
    }
  }

  /** Scan DB and add watchers for any thread we don't yet track, starting from EOF. */
  private initWatchers(): void {
    try {
      if (!fs.existsSync(CODEX_DB_PATH)) return;
      const db = new DatabaseSync(CODEX_DB_PATH, { readOnly: true });
      const rows = db.prepare(
        `SELECT id, rollout_path FROM threads WHERE COALESCE(archived,0)=0 AND rollout_path IS NOT NULL`
      ).all() as Array<{ id: string; rollout_path: string }>;
      db.close();

      for (const row of rows) {
        if (this.watchers.has(row.id)) continue;
        if (!fs.existsSync(row.rollout_path)) continue;
        const stat = fs.statSync(row.rollout_path);
        this.watchers.set(row.id, {
          rolloutPath: row.rollout_path,
          lastOffset: stat.size, // start from now — only future writes
          threadId: row.id,
        });
      }
    } catch (err) {
      console.error('[remote-monitor] initWatchers error:', err instanceof Error ? err.message : err);
    }
  }

  private poll(): void {
    const now = Date.now();

    // Periodically refresh watcher list to pick up newly created threads
    if (now - this.lastRefresh > REFRESH_TARGETS_EVERY_MS) {
      this.initWatchers();
      this.lastRefresh = now;
    }

    if (!this.sendFn || this.enabledChats.size === 0) return;

    // Build threadId → { slot, workspaceName } from the live target list
    const slotMap = new Map<string, { slot: string; workspaceName: string }>();
    try {
      for (const t of this.getTargets()) {
        slotMap.set(t.threadId, { slot: t.slot, workspaceName: t.workspaceName });
      }
    } catch { /* DB busy or unreachable — skip this tick */ }

    for (const [threadId, watcher] of this.watchers) {
      try {
        if (!fs.existsSync(watcher.rolloutPath)) continue;
        const stat = fs.statSync(watcher.rolloutPath);
        if (stat.size <= watcher.lastOffset) continue;

        const fd = fs.openSync(watcher.rolloutPath, 'r');
        const chunk = Buffer.alloc(stat.size - watcher.lastOffset);
        fs.readSync(fd, chunk, 0, chunk.length, watcher.lastOffset);
        fs.closeSync(fd);
        watcher.lastOffset = stat.size;

        const { texts, outputTokens } = extractFromChunk(chunk.toString('utf-8'));
        if (texts.length === 0) continue;

        const combined = texts.join('\n').trim();
        const info = slotMap.get(threadId);
        const slot = info?.slot ?? '?';
        const ws = info?.workspaceName ?? threadId.slice(0, 8);

        // Preview: first 200 chars
        const preview = combined.length > 200 ? `${combined.slice(0, 197)}…` : combined;
        const tokenNote = outputTokens > 0 ? `（本轮 ${outputTokens} tokens）` : '';

        const notification = [
          `📩 来自 [${ws}] 的 #${slot} 线程有新回复${tokenNote}：`,
          '',
          preview,
          '',
          `💬 用 #${slot} 你的消息 快速回复该线程`,
        ].join('\n');

        for (const chatId of this.enabledChats) {
          this.sendFn(chatId, notification).catch((err) => {
            console.error('[remote-monitor] send error:', err instanceof Error ? err.message : err);
          });
        }
      } catch { /* skip individual watcher errors */ }
    }
  }
}
