/**
 * RemoteMonitor — watches Codex rollout JSONL files for new AI messages
 * generated by the desktop Codex client, then pushes them to Feishu.
 *
 * Rollout event format (desktop Codex):
 *   { type: 'event_msg', payload: { type: 'agent_message', message: '...', phase: 'commentary'|'final_answer' } }
 *   { type: 'event_msg', payload: { type: 'token_count',   info: { last_token_usage: { output_tokens, reasoning_output_tokens } } } }
 *   { type: 'event_msg', payload: { type: 'task_started' } }
 *   { type: 'event_msg', payload: { type: 'task_complete' } }
 *
 * Modes:
 *   default  → send only final_answer messages, once per turn (on task_complete)
 *   stream   → also send commentary messages as they arrive
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { DatabaseSync } from 'node:sqlite';
import type { Target } from './types.js';

const CODEX_DB_PATH = path.join(os.homedir(), '.codex', 'state_5.sqlite');
const POLL_INTERVAL_MS = 2500;
const REFRESH_TARGETS_EVERY_MS = 30_000;

type SendFn = (chatId: string, text: string) => Promise<void>;
type GetTargets = () => Target[];

type ChatMode = 'final' | 'stream';

interface WatchEntry {
  rolloutPath: string;
  lastOffset: number;
  threadId: string;
  /** Buffered final_answer messages for the current in-progress turn */
  pendingFinal: string[];
  /** Accumulated output tokens for the current turn */
  pendingTokens: number;
}

interface RolloutEvent {
  kind: 'task_started' | 'task_complete' | 'commentary' | 'final_answer' | 'token_count';
  text?: string;       // for commentary / final_answer
  tokens?: number;     // for token_count
}

/** Parse newly-appended JSONL bytes into structured rollout events. */
function parseChunk(raw: string): RolloutEvent[] {
  const events: RolloutEvent[] = [];
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      const obj = JSON.parse(trimmed) as Record<string, unknown>;
      if (obj.type !== 'event_msg') continue;
      const p = obj.payload as Record<string, unknown> | undefined;
      if (!p) continue;

      switch (p.type) {
        case 'task_started':
          events.push({ kind: 'task_started' });
          break;
        case 'task_complete':
          events.push({ kind: 'task_complete' });
          break;
        case 'agent_message': {
          if (typeof p.message !== 'string' || !p.message) continue;
          const phase = p.phase as string | undefined;
          events.push({
            kind: phase === 'final_answer' ? 'final_answer' : 'commentary',
            text: p.message,
          });
          break;
        }
        case 'token_count': {
          const info = p.info as Record<string, unknown> | undefined;
          const last = info?.last_token_usage as Record<string, unknown> | undefined;
          if (last) {
            events.push({
              kind: 'token_count',
              tokens: Number(last.output_tokens ?? 0) + Number(last.reasoning_output_tokens ?? 0),
            });
          }
          break;
        }
      }
    } catch { /* skip malformed lines */ }
  }
  return events;
}

export class RemoteMonitor {
  private watchers = new Map<string, WatchEntry>();
  /** chatId → mode ('final' or 'stream') */
  private enabledChats = new Map<string, ChatMode>();
  /** threadIds currently being handled by the bridge — suppress monitor notifications for these */
  private suppressedThreadIds = new Set<string>();
  private sendFn: SendFn | null = null;
  private pollTimer: NodeJS.Timeout | null = null;
  private lastRefresh = 0;

  constructor(private readonly getTargets: GetTargets) {}

  setSendFn(fn: SendFn): void {
    this.sendFn = fn;
  }

  /**
   * Toggle remote mode for a chatId.
   * mode: 'final' (default) or 'stream' (include commentary)
   * Returns true if now enabled, false if now disabled.
   */
  toggle(chatId: string, mode: ChatMode = 'final'): boolean {
    const current = this.enabledChats.get(chatId);
    if (current !== undefined) {
      // If same mode: turn off. If different mode: switch.
      if (current === mode) {
        this.enabledChats.delete(chatId);
        if (this.enabledChats.size === 0) this.stopPolling();
        return false;
      }
      this.enabledChats.set(chatId, mode);
      return true;
    }
    this.enabledChats.set(chatId, mode);
    this.initWatchers();
    this.ensurePolling();
    return true;
  }

  getMode(chatId: string): ChatMode | undefined {
    return this.enabledChats.get(chatId);
  }

  isEnabled(chatId: string): boolean {
    return this.enabledChats.has(chatId);
  }

  /**
   * Suppress notifications for a threadId while the bridge is actively handling it.
   * Call before sendToThread; call unsuppress() in finally.
   */
  suppress(threadId: string): void {
    this.suppressedThreadIds.add(threadId);
  }

  unsuppress(threadId: string): void {
    this.suppressedThreadIds.delete(threadId);
  }

  private ensurePolling(): void {
    if (this.pollTimer) return;
    this.pollTimer = setInterval(() => this.poll(), POLL_INTERVAL_MS);
  }

  private stopPolling(): void {
    if (this.pollTimer) {
      clearInterval(this.pollTimer);
      this.pollTimer = null;
    }
  }

  private initWatchers(): void {
    try {
      if (!fs.existsSync(CODEX_DB_PATH)) return;
      const db = new DatabaseSync(CODEX_DB_PATH, { readOnly: true });
      const rows = db.prepare(
        `SELECT id, rollout_path FROM threads WHERE COALESCE(archived,0)=0 AND rollout_path IS NOT NULL`
      ).all() as Array<{ id: string; rollout_path: string }>;
      db.close();

      for (const row of rows) {
        if (this.watchers.has(row.id)) continue;
        if (!fs.existsSync(row.rollout_path)) continue;
        const stat = fs.statSync(row.rollout_path);
        this.watchers.set(row.id, {
          rolloutPath: row.rollout_path,
          lastOffset: stat.size,
          threadId: row.id,
          pendingFinal: [],
          pendingTokens: 0,
        });
      }
    } catch (err) {
      console.error('[remote-monitor] initWatchers error:', err instanceof Error ? err.message : err);
    }
  }

  private notify(chatId: string, threadId: string, slotMap: Map<string, { slot: string; workspaceName: string }>, text: string, tokens: number, isStream: boolean): void {
    // Skip if the bridge is currently handling this thread (avoid duplicate delivery)
    if (this.suppressedThreadIds.has(threadId)) return;

    const info = slotMap.get(threadId);
    const slot = info?.slot ?? '?';
    const ws = info?.workspaceName ?? threadId.slice(0, 8);
    const tokenNote = tokens > 0 ? `（${tokens} tokens）` : '';
    const label = isStream ? `💭 [${ws}] #${slot} 过程` : `📩 [${ws}] #${slot} 回复${tokenNote}`;
    // Send full text — no truncation
    const notification = [
      `${label}：`,
      '',
      text,
      '',
      `💬 用 #${slot} 你的消息 快速回复`,
    ].join('\n');

    this.sendFn!(chatId, notification).catch((err) => {
      console.error('[remote-monitor] send error:', err instanceof Error ? err.message : err);
    });
  }

  private poll(): void {
    const now = Date.now();
    if (now - this.lastRefresh > REFRESH_TARGETS_EVERY_MS) {
      this.initWatchers();
      this.lastRefresh = now;
    }
    if (!this.sendFn || this.enabledChats.size === 0) return;

    const slotMap = new Map<string, { slot: string; workspaceName: string }>();
    try {
      for (const t of this.getTargets()) slotMap.set(t.threadId, { slot: t.slot, workspaceName: t.workspaceName });
    } catch { return; }

    for (const [threadId, watcher] of this.watchers) {
      try {
        if (!fs.existsSync(watcher.rolloutPath)) continue;
        const stat = fs.statSync(watcher.rolloutPath);
        if (stat.size <= watcher.lastOffset) continue;

        const fd = fs.openSync(watcher.rolloutPath, 'r');
        const chunk = Buffer.alloc(stat.size - watcher.lastOffset);
        fs.readSync(fd, chunk, 0, chunk.length, watcher.lastOffset);
        fs.closeSync(fd);
        watcher.lastOffset = stat.size;

        const events = parseChunk(chunk.toString('utf-8'));
        if (events.length === 0) continue;

        for (const event of events) {
          switch (event.kind) {
            case 'task_started':
              // New turn — clear previous turn's pending buffer
              watcher.pendingFinal = [];
              watcher.pendingTokens = 0;
              break;

            case 'token_count':
              watcher.pendingTokens += event.tokens ?? 0;
              break;

            case 'commentary':
              // Stream mode only: emit commentary immediately
              for (const [chatId, mode] of this.enabledChats) {
                if (mode === 'stream') {
                  this.notify(chatId, threadId, slotMap, event.text!, 0, true);
                }
              }
              break;

            case 'final_answer':
              // Buffer the final answer — will be sent on task_complete
              watcher.pendingFinal.push(event.text!);
              break;

            case 'task_complete': {
              // Emit buffered final answer (if any) to all enabled chats
              if (watcher.pendingFinal.length > 0) {
                const text = watcher.pendingFinal.join('\n').trim();
                const tokens = watcher.pendingTokens;
                for (const [chatId] of this.enabledChats) {
                  this.notify(chatId, threadId, slotMap, text, tokens, false);
                }
              }
              watcher.pendingFinal = [];
              watcher.pendingTokens = 0;
              break;
            }
          }
        }
      } catch { /* skip individual watcher errors */ }
    }
  }
}
